### ISSUE TITLE
cant find Tanks in the roster tab

### ISSUE THREAD

**Issue by rerodesign** [BSData/tanks-the-modern-age#3]
**Describe the bug**
I downloaded the Tanks data and it is shown in the Data tab but I cant choose it to make a roster.
**To Reproduce**
1. Go to Manage Data, add Tanks.
2. Then create an new roster.
3. looking for Tanks.

**Screenshots**
![Tankserror](https://user-images.githubusercontent.com/81778249/138597293-c75ede94-e620-495c-a1e7-bedcc5358c0d.PNG)
![Tankserror2](https://user-images.githubusercontent.com/81778249/138597305-e76bcac1-59b2-4043-b3de-6bfd34c6e8f0.PNG)

**Device and data (please complete the following information):**
 - OS: Win10
 - BattleScribe version [e.g. 2.03.21]

**Comment by zeroxjason** [comment]
Hello,

Sorry for the delay in getting back to you.

Tanks Modern Age data is under 'GF9 Tanks: The Modern Age' to match with their WW2 game, 'GF9: Tanks'.

![image](https://user-images.githubusercontent.com/19592500/143665800-a461984b-1218-4ab9-aa9a-bd5b681fde18.png)
