### ISSUE TITLE
American custom vehicles missing

### ISSUE THREAD

**Issue by Quasihodo** [BSData/tanks-the-modern-age#4]
**Describe the bug**

The custom soviet units are implemented but the american ones are not

![tanks](https://user-images.githubusercontent.com/89463534/167804066-441cfa27-b7d6-4086-974d-4e5a7c33e59b.jpg)

**Device and data (please complete the following information):**
 - OS: windows 10
 - BattleScribe version 2.0.3.21
 - Release version [e.g. v1.2.3]

**Comment by zeroxjason** [comment]
Good spot, I think my workflow got messed up and I overwrote my files.

I have added the two USA custom units and also the German Jaguar 1. 

Hopefully should all be fixed now!
